# yaml-language-server: $schema=https://aka.ms/configuration-dsc-schema/0.2
# To use this script download locally and run "winget configure -f <C:/Users/<username>/winget-configs/config-file-name.dsc.yaml>" in powershell.
properties:
  assertions:
    - resource: Microsoft.Windows.Developer/OsVersion
      directives:
        description: Verify min OS version requirement
        allowPrerelease: true
      settings:
        MinVersion: '10.0.22000'
  resources:
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Installing Microsoft.VisualStudioCode
        allowPrerelease: true
        securityContext: elevated
      settings:
        id: "Microsoft.VisualStudioCode"
        source: winget
        ensure: Present
      id: Microsoft.VisualStudioCode

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Installing Microsoft.VisualStudio.Enterprise
        allowPrerelease: true
        securityContext: elevated
      settings:
        id: "Microsoft.VisualStudio.Enterprise"
        source: winget
        ensure: Present
      id: Microsoft.VisualStudio.Enterprise

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Installing Microsoft.PowerShell
        allowPrerelease: true
        securityContext: elevated
      settings:
        id: "Microsoft.PowerShell"
        source: winget
        ensure: Present
      id: Microsoft.PowerShell

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Installing Git.Git
        allowPrerelease: true
        securityContext: elevated
      settings:
        id: "Git.Git"
        source: winget
        ensure: Present
      id: Git.Git

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Installing Microsoft.SQLServerManagementStudio
        allowPrerelease: true
        securityContext: elevated
      settings:
        id: "Microsoft.SQLServerManagementStudio.22"
        source: winget
        ensure: Present
      id: Microsoft.SQLServerManagementStudio.22

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Installing 7zip.7zip
        allowPrerelease: true
        securityContext: elevated
      settings:
        id: "7zip.7zip"
        source: winget
        ensure: Present
      id: 7zip.7zip

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Installing PuTTY.PuTTY
        allowPrerelease: true
        securityContext: elevated
      settings:
        id: "PuTTY.PuTTY"
        source: winget
        ensure: Present
      id: PuTTY.PuTTY

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Installing Postman.Postman
        allowPrerelease: true
        securityContext: elevated
      settings:
        id: "Postman.Postman"
        source: winget
        ensure: Present
      id: Postman.Postman
        
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Installing Microsoft To-Do
        allowPrerelease: true
        securityContext: elevated
      settings:
        id: "9NBLGGH5R558"
        source: msstore
        ensure: Present
      id: 9NBLGGH5R558

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Installing Microsoft Whiteboard
        allowPrerelease: true
        securityContext: elevated
      settings:
        id: "9MSPC6MP8FM4"
        source: msstore
        ensure: Present
      id: 9MSPC6MP8FM4

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Installing Microsoft.Azd
        allowPrerelease: true
        securityContext: elevated
      settings:
        id: "Microsoft.Azd"
        source: winget
        ensure: Present
      id: Microsoft.Azd

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Installing Microsoft.Azure.AZCopy.10
        allowPrerelease: true
        securityContext: elevated
      settings:
        id: "Microsoft.Azure.AZCopy.10"
        source: winget
        ensure: Present
      id: Microsoft.Azure.AZCopy.10

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Installing ChatGPT
        allowPrerelease: true
        securityContext: elevated
      settings:
        id: "9NT1R1C2HH7J"
        source: msstore
        ensure: Present
      id: 9NT1R1C2HH7J

    # - resource: Microsoft.WinGet.DSC/WinGetPackage
    #   directives:
    #     description: Installing Microsoft.PowerBI
    #     allowPrerelease: true
    #     securityContext: elevated
    #   settings:
    #     id: "Microsoft.PowerBI"
    #     source: winget
    #     ensure: Present
    #   id: Microsoft.PowerBI

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Installing Spotify
        allowPrerelease: true
        securityContext: elevated
      settings:
        id: "9NCBCSZSJRSB"
        source: msstore
        ensure: Present
      id: 9NCBCSZSJRSB

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Installing Google.Chrome
        allowPrerelease: true
        securityContext: elevated
      settings:
        id: "Google.Chrome"
        source: winget
        ensure: Present
      id: Google.Chrome

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Installing Microsoft.DotNet.SDK.10
        allowPrerelease: true
        securityContext: elevated
      settings:
        id: "Microsoft.DotNet.SDK.10"
        source: winget
        ensure: Present
      id: Microsoft.DotNet.SDK.10

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Installing Fastfetch-cli.Fastfetch
        allowPrerelease: true
        securityContext: elevated
      settings:
        id: "Fastfetch-cli.Fastfetch"
        source: winget
        ensure: Present
      id: Fastfetch-cli.Fastfetch

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Installing WinDirStat.WinDirStat
        allowPrerelease: true
        securityContext: elevated
      settings:
        id: "WinDirStat.WinDirStat"
        source: winget
        ensure: Present
      id: WinDirStat.WinDirStat

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Installing Microsoft.WindowsTerminal
        allowPrerelease: true
        securityContext: elevated
      settings:
        id: "Microsoft.WindowsTerminal"
        source: winget
        ensure: Present
      id: Microsoft.WindowsTerminal

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Installing WinSCP.WinSCP
        allowPrerelease: true
        securityContext: elevated
      settings:
        id: "WinSCP.WinSCP"
        source: winget
        ensure: Present
      id: WinSCP.WinSCP

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Installing Microsoft.Azure.StorageExplorer
        allowPrerelease: true
        securityContext: elevated
      settings:
        id: "Microsoft.Azure.StorageExplorer"
        source: winget
        ensure: Present
      id: Microsoft.Azure.StorageExplorer

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Installing Databricks.DatabricksCLI
        allowPrerelease: true
        securityContext: elevated
      settings:
        id: "Databricks.DatabricksCLI"
        source: winget
        ensure: Present
      id: Databricks.DatabricksCLI

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Installing Microsoft.AzureCLI
        allowPrerelease: true
        securityContext: elevated
      settings:
        id: "Microsoft.AzureCLI"
        source: winget
        ensure: Present
      id: Microsoft.AzureCLI
        
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Installing Starship.Starship
        allowPrerelease: true
        securityContext: elevated
      settings:
        id: "Starship.Starship"
        source: winget
        ensure: Present
      id: Starship.Starship
    
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Installing Make
        allowPrerelease: true
        securityContext: elevated
      settings:
        id: "GnuWin32.Make"
        source: winget
        ensure: Present
      id: GnuWin32.Make

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Installing Microsoft WSL
        allowPrerelease: true
        securityContext: current
      settings:
        id: "Microsoft.WSL"
        source: winget
      id: Microsoft.WSL
  configurationVersion: 0.2.0

