dev_packages:
  - python3
  - python3-venv
  - python3-pip
  - pipx
  - nodejs
  - npm
  - powershell
  - bat
  - fzf
  - cmatrix
  - zoxide
  - direnv
  - eza
  - jq

docker_enabled: true

# tfenv repo
tfenv_repo: 'https://github.com/tfutils/tfenv.git'